### ISSUE TITLE
Deploy Dittofeed to ECS

### ISSUE THREAD

**Issue by pcr0wley** [crowleysystems/dittofeed#1]
This issue is to deploy Metabase to ECS. Currently it is running in Docker on EC2. Aside from the main Dittofeed instance we also need to deploy Temporal.

Currently it is in Single Tenant mode, which just means there is a single username and password for everyone. Eventually we will set it up as multi-tenant with SAML authentication.

### `docker-compose.pilot.yaml`
```
# CUSTOM VERSION TO USE EXTERNAL POSTGRESQL AND CLICKHOUSE DATABASES
# DEPENDS ON CUSTOM DOCKERFILE IN packages/lite/Dockerfile
version: "3.9"
x-database-credentials: &database-credentials
  DATABASE_USER: ${DATABASE_USER:-postgres}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
x-clickhouse-credentials: &clickhouse-credentials
  CLICKHOUSE_USER: ${CLICKHOUSE_USER:-dittofeed}
  CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}
x-backend-app-env: &backend-app-env
  <<: [*clickhouse-credentials, *database-credentials]
  NODE_ENV: production
  DATABASE_HOST: ${DATABASE_HOST:-postgres}
  DATABASE_PORT: ${DATABASE_PORT:-5432}
  CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-http://clickhouse-server:8123}
  TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS:-temporal:7233}
  WORKSPACE_NAME: ${WORKSPACE_NAME:-Default}
  DASHBOARD_URL: ${DASHBOARD_URL}
  DASHBOARD_API_BASE: ${DASHBOARD_API_BASE}
  SECRET_KEY: ${SECRET_KEY}
  PASSWORD: ${PASSWORD}

services:
  lite:
    build:
      context: .
      dockerfile: ./packages/lite/Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - temporal
    environment:
      <<: *backend-app-env
      LOG_LEVEL: debug
    networks:
      - dittofeed-network-lite
  temporal:
    container_name: temporal
    environment:
      - DB=postgresql
      - DB_PORT=${DATABASE_PORT:-5432}
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PWD=${DATABASE_PASSWORD:-password}
      - POSTGRES_SEEDS=${DATABASE_HOST:-postgres}
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/prod.yaml
    image: temporalio/auto-setup:${TEMPORAL_VERSION:-1.18.5}
    labels:
      kompose.volume.type: configMap
    networks:
      - dittofeed-network-lite
    ports:
      - 7233:7233
    volumes:
      - ./packages/backend-lib/temporal-dynamicconfig:/etc/temporal/config/dynamicconfig

networks:
  dittofeed-network-lite:
    driver: bridge
    name: dittofeed-network-lite
```

### `.env`
```
# used to generate links to the dashboard e.g. for unsubscribe links.
DASHBOARD_URL="https://marketing.crowleymarine.com"
# used to issue requests to the api from the dashboard.
DASHBOARD_API_BASE="https://marketing.crowleymarine.com"

# PostgreSQL
DATABASE_HOST=HOST
DATABASE_USER=dittofeed
DATABASE_PASSWORD=PASSWORD

# ClickHouse
CLICKHOUSE_HOST=https://HOST:8443
CLICKHOUSE_USER=dittofeed
CLICKHOUSE_PASSWORD=PASSWORD

# Single-tenant credentials
SECRET_KEY=secret_key
PASSWORD=password
```
